import { defineConfig, fontProviders } from 'astro/config';
import svelte from '@astrojs/svelte';
import cloudflare from '@astrojs/cloudflare';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  // Cloudflare Workers adapter — `output:'server'` is required by
  // @astrojs/cloudflare.  Every page in this site uses
  // `export const prerender = true`, so all HTML is statically generated
  // at build time and served from the ASSETS binding.  The SSR runtime
  // exists only to serve the custom API routes in src/worker.ts.
  // prerenderEnvironment:'node' uses Astro's default Node.js prerenderer so
  // the custom src/worker.ts entry is not used as the prerender server.
  output: 'server',
  adapter: cloudflare({ prerenderEnvironment: 'node' }),

  site: 'https://bloqr.ai',

  // ── Astro 6 Fonts API ──────────────────────────────────────────────────
  // Uses the fontsource() provider to self-host fonts from the installed
  // @fontsource npm packages.  The Font component in BaseHead injects
  // @font-face rules, preload <link> tags, and the CSS custom properties
  // (--font-display, --font-mono) consumed by global.css and components.
  fonts: [
    {
      name: 'Space Grotesk',
      cssVariable: '--font-display',
      provider: fontProviders.fontsource(),
      weights: [400, 500, 600, 700],
      styles: ['normal'],
      display: 'swap',
      fallbacks: ['system-ui', 'sans-serif'],
    },
    {
      name: 'JetBrains Mono',
      cssVariable: '--font-mono',
      provider: fontProviders.fontsource(),
      weights: [400, 500, 700],
      styles: ['normal'],
      display: 'swap',
      fallbacks: ['monospace'],
    },
  ],

  // ── Astro 6 Security ───────────────────────────────────────────────────
  // checkOrigin guards against CSRF on form actions.
  // csp auto-hashes inline scripts/styles so a strict CSP can be enforced
  // without 'unsafe-inline'.  Production CSP headers are applied in
  // src/worker.ts via applyCSP(), which adds hardening directives
  // (frame-ancestors, base-uri, form-action) at the edge.
  security: {
    checkOrigin: true,
    csp: {
      algorithm: 'SHA-256',
    },
  },

  // ── Markdown / Code Highlighting ──────────────────────────────────────
  // Uses Shiki 4 (bundled with Astro 6) with dual dark/light themes so that
  // highlighted code blocks emit CSS custom properties (--shiki-dark / --shiki-light)
  // via inline `style` attributes on each token element.  The global.css Shiki
  // section maps these CSS vars to actual colours based on prefers-color-scheme.
  // Note: `defaultColor:false` moves colour declarations into CSS variables but
  // still uses inline `style` attributes for them — `style-src` must still allow
  // inline styles (via 'unsafe-inline') for code blocks to render correctly.
  // The stylesheet that maps these CSS vars to actual colours is in
  // src/styles/global.css under the "Shiki dual-theme" section.
  markdown: {
    syntaxHighlight: {
      type: 'shiki',
      excludeLangs: [],
    },
    shikiConfig: {
      // houston: Astro's own dark theme — matches the Bloqr dark palette well.
      // vitesse-light: clean minimal light theme for light-mode users.
      // defaultColor:false — outputs CSS variables via inline style attributes (not raw colour values).
      // Inline styles are still emitted; style-src must allow them.
      themes: {
        dark:  'houston',
        light: 'vitesse-light',
      },
      defaultColor: false,
      wrap: true,
    },
  },

  // ── Note on experimental features ─────────────────────────────────────
  // experimental.rustCompiler and experimental.queuedRendering are NOT
  // valid Astro 6.1.x config keys and caused build failures when present.
  // The Rust compiler is enabled via the @astrojs/compiler-rs package
  // (already in dependencies) — it does not require an experimental flag.
  // Per-route caching must be configured in src/worker.ts directly since
  // pages are served via env.ASSETS.fetch() from the ASSETS binding, not
  // through adapter-level route rules.

  integrations: [
    svelte(),
    sitemap(),
  ],

  vite: {
    server: {
      headers: {
        // Dev-only CSP — permissive to allow Vite's HMR inline style/script
        // injection during local development.  Production CSP is stricter:
        // inline hashes are auto-generated by security.csp above and
        // hardening directives are added by applyCSP() in src/worker.ts.
        'Content-Security-Policy': "default-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://app.posthog.com https://plausible.io; img-src 'self' data:;",
      }
    }
  }
});
