import { defineConfig, fontProviders } from 'astro/config';
import svelte from '@astrojs/svelte';
import cloudflare from '@astrojs/cloudflare';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  // Cloudflare Workers adapter — `output:'server'` is required by
  // @astrojs/cloudflare.  Every page in this site uses
  // `export const prerender = true`, so all HTML is statically generated
  // at build time and served from the ASSETS binding.  The SSR runtime
  // exists only to serve the custom API routes in src/worker.ts.
  // prerenderEnvironment:'node' uses Astro's default Node.js prerenderer so
  // the custom src/worker.ts entry is not used as the prerender server.
  output: 'server',
  adapter: cloudflare({ prerenderEnvironment: 'node' }),

  site: 'https://bloqr.ai',

  // ── Astro 6 Fonts API ──────────────────────────────────────────────────
  // Uses the fontsource() provider to self-host fonts from the installed
  // @fontsource npm packages.  The Font component in BaseHead injects
  // @font-face rules, preload <link> tags, and the CSS custom properties
  // (--font-display, --font-mono) consumed by global.css and components.
  fonts: [
    {
      name: 'Space Grotesk',
      cssVariable: '--font-display',
      provider: fontProviders.fontsource(),
      weights: [400, 500, 600, 700],
      styles: ['normal'],
      display: 'swap',
      fallbacks: ['system-ui', 'sans-serif'],
    },
    {
      name: 'JetBrains Mono',
      cssVariable: '--font-mono',
      provider: fontProviders.fontsource(),
      weights: [400, 500, 700],
      styles: ['normal'],
      display: 'swap',
      fallbacks: ['monospace'],
    },
  ],

  // ── Astro 6 Security ───────────────────────────────────────────────────
  // checkOrigin guards against CSRF on form actions.
  // csp auto-hashes inline scripts/styles so a strict CSP can be enforced
  // without 'unsafe-inline'.  Production CSP headers are set in
  // wrangler.toml (or Cloudflare dashboard) for proper edge delivery.
  security: {
    checkOrigin: true,
    csp: {
      algorithm: 'SHA-256',
    },
  },

  // ── Markdown / Code Highlighting ──────────────────────────────────────
  // Uses Shiki 4 (bundled with Astro 6) with dual dark/light themes so that
  // highlighted code blocks use CSS custom properties (--shiki-dark / --shiki-light)
  // instead of inline styles.  This makes code blocks fully CSP-compatible
  // — no 'unsafe-inline' is needed for syntax highlighting.
  // The stylesheet that maps these CSS vars to actual colours is in
  // src/styles/global.css under the "Shiki dual-theme" section.
  markdown: {
    syntaxHighlight: {
      type: 'shiki',
      excludeLangs: [],
    },
    shikiConfig: {
      // houston: Astro's own dark theme — matches the Bloqr dark palette well.
      // vitesse-light: clean minimal light theme for light-mode users.
      // defaultColor:false triggers CSS-variable output (CSP-safe, no inline styles).
      themes: {
        dark:  'houston',
        light: 'vitesse-light',
      },
      defaultColor: false,
      wrap: true,
    },
  },

  // ── Astro 6 Experimental Features ─────────────────────────────────────
  experimental: {
    // Rust-based Astro compiler — faster .astro file transformation.
    // Drop-in replacement; no API changes required.
    rustCompiler: true,

    // Queued rendering — serialises concurrent SSR renders so the Node.js
    // event loop is never overwhelmed during prerendering.  contentCache
    // caches rendered HTML across rebuilds to speed up incremental builds.
    queuedRendering: {
      enabled:      true,
      contentCache: true,
    },

    // Per-route cache hints — tells the adapter how long to cache each route.
    // All landing pages are fully static (prerendered), so long TTLs are safe.
    // API / admin routes are omitted (they require fresh responses).
    routeRules: {
      '/':              { maxAge: 3600,  swr: 86400 },
      '/blog':          { maxAge: 3600,  swr: 86400 },
      '/blog/**':       { maxAge: 86400, swr: 604800 },
      '/changelog':     { maxAge: 3600,  swr: 86400 },
      '/about':         { maxAge: 86400, swr: 604800 },
      '/vpn-myths':     { maxAge: 86400, swr: 604800 },
      '/why-not-private': { maxAge: 86400, swr: 604800 },
      '/privacy':       { maxAge: 86400, swr: 604800 },
      '/terms':         { maxAge: 86400, swr: 604800 },
    },
  },

  integrations: [
    svelte(),
    sitemap(),
  ],

  vite: {
    server: {
      headers: {
        // Dev-only CSP — permissive to allow Vite's HMR inline style/script
        // injection during local development.  Production CSP is stricter:
        // inline hashes are auto-generated by security.csp above and
        // delivered via the Cloudflare Worker response headers.
        'Content-Security-Policy': "default-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://app.posthog.com https://plausible.io;"
      }
    }
  }
});
