import { defineConfig, fontProviders } from 'astro/config';
import svelte from '@astrojs/svelte';
import cloudflare from '@astrojs/cloudflare';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  // Cloudflare Workers adapter — `output:'server'` is required by
  // @astrojs/cloudflare.  Every page in this site uses
  // `export const prerender = true`, so all HTML is statically generated
  // at build time and served from the ASSETS binding.  The SSR runtime
  // exists only to serve the custom API routes in src/worker.ts.
  // prerenderEnvironment:'node' uses Astro's default Node.js prerenderer so
  // the custom src/worker.ts entry is not used as the prerender server.
  output: 'server',
  adapter: cloudflare({ prerenderEnvironment: 'node' }),

  site: 'https://bloqr.ai',

  // ── Astro 6 Fonts API ──────────────────────────────────────────────────
  // Uses the fontsource() provider to self-host fonts from the installed
  // @fontsource npm packages.  The Font component in BaseHead injects
  // @font-face rules, preload <link> tags, and the CSS custom properties
  // (--font-display, --font-mono) consumed by global.css and components.
  fonts: [
    {
      name: 'Space Grotesk',
      cssVariable: '--font-display',
      provider: fontProviders.fontsource(),
      weights: [400, 500, 600, 700],
      styles: ['normal'],
      display: 'swap',
      fallbacks: ['system-ui', 'sans-serif'],
    },
    {
      name: 'JetBrains Mono',
      cssVariable: '--font-mono',
      provider: fontProviders.fontsource(),
      weights: [400, 500, 700],
      styles: ['normal'],
      display: 'swap',
      fallbacks: ['monospace'],
    },
  ],

  // ── Astro 6 Security ───────────────────────────────────────────────────
  // checkOrigin guards against CSRF on form actions.
  // csp auto-hashes inline scripts/styles so a strict CSP can be enforced
  // without 'unsafe-inline'.  Production CSP headers are set in
  // wrangler.toml (or Cloudflare dashboard) for proper edge delivery.
  security: {
    checkOrigin: true,
    csp: {
      algorithm: 'SHA-256',
    },
  },

  integrations: [
    svelte(),
    sitemap(),
  ],

  vite: {
    server: {
      headers: {
        // Dev-only CSP — permissive to allow Vite's HMR inline style/script
        // injection during local development.  Production CSP is stricter:
        // inline hashes are auto-generated by security.csp above and
        // delivered via the Cloudflare Worker response headers.
        'Content-Security-Policy': "default-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://app.posthog.com https://plausible.io;"
      }
    }
  }
});
